import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "client website",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-white`}>
				{children}
				<script
					src="https://sandbox.karini.ai/chatbot-script.js"
					data-id="karini_chatbot"
					data-bot_name="copper QnA"
					data-bot_avatar=""
					data-description="question answering chatbot for copper assesment"
					data-welcome_message="hi, how can I help you?"
					data-failure_message="Sorry, I don't have knowledge regarding this"
					data-apikey="KARINI_655c5a419d7a15c10d9d6047_f9af0447375c181612f3d3bff6b600e569bf5b6325d08e8ff13e265717646d17"
					data-widget_size="normal"
					data-theme_color="#dc2626"
					defer
				></script>
			</body>
		</html>
	);
}
