import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "client website",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-white`}>
				{children}
				<script
					src="https://sandbox.karini.ai/chatbot-script.js"
					data-id="karini_chatbot"
					data-bot_name="Chatbot sandbox"
					data-bot_avatar="https://cdn-icons-png.flaticon.com/512/4712/4712139.png"
					data-description="ACME Enterprise Support Copilot"
					data-welcome_message="Welcome to Enterprise Support!"
					data-failure_message="There was an error"
					data-apikey="KARINI_653fa72298cee389640966ec_f9af0447375c181612f3d3bff6b600e5d3b048d8a3f085f0d307d46a8075c349"
					data-widget_size="normal"
					data-theme_color="#7c3aed"
					defer
				></script>
			</body>
		</html>
	);
}
